apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
  labels:
    app.kubernetes.io/part-of: shop
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
